name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore Packages
      run: nuget restore src.2026\Nord2026Plus.slnx

    - name: Build Extension
      run: msbuild src.2026\Nord2026Plus.slnx /p:Configuration=Release /t:Rebuild
      env:
        DeployExtension: False

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./package.json

    - name: Generate changelog
      id: changelog
      continue-on-error: true
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Copy VSIX to Releases
      uses: softprops/action-gh-release@v2
      id: create_release
      if: steps.create_tag.outputs.successful
      with:
        draft: false
        prerelease: false
        tag_name: ${{ steps.create_tag.outputs.version }}
        files: |
          src.2026\bin\Release\Nord2026Plus.vsix
        body: |
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
